name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/NumberExtensions.sln
      - name: Build
        run: dotnet build --no-restore -c Release src/NumberExtensions.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release src/NumberExtensions.sln